--local _, addon = ...
--local AceGUI = LibStub("AceGUI-3.0")
--
---- Create the frame container
--local frame = AceGUI:Create("Frame")
--frame:SetTitle("Example Frame")
--frame:SetStatusText("AceGUI-3.0 Example Container Frame")
--frame:SetCallback("OnClose", function(widget) AceGUI:Release(widget) end)
--frame:SetLayout("Fill")
--frame.frame:SetBackdropColor(1, 0, 0)
--frame.frame:SetBackdropBorderColor(0, 1, 0)
--
--local btn = AceGUI:Create("Button")
--btn:SetWidth(170)
--btn:SetText("Button !")
--btn:SetCallback("OnClick", function()
--    print('clicked')
--    for k, v in pairs(frame) do
--       print(k)
--    end
--end)
---- Add the button to the container
--frame:AddChild(btn)
--
---- Create the TabGroup
--local tab =  AceGUI:Create("TabGroup")
--tab:SetLayout("List")
---- Setup which tabs to show
--tab:SetTabs({{text="Tab 1", value="tab1"}, {text="Tab 2", value="tab2"}})
---- Register callback
--tab:SetCallback("OnGroupSelected", SelectGroup)
---- Set initial Tab (this will fire the OnGroupSelected callback)
--tab:SelectTab("tab1")
--
---- add to the frame container
--frame:AddChild(tab)
--
--
--
----local function DrawGroup1(container)
----    local desc = AceGUI:Create("Label")
----    desc:SetText("This is Tab 1")
----    desc:SetFullWidth(true)
----    container:AddChild(desc)
----
----    local button = addon.CreateRealAceButton('Button', 200)
----    button:SetCallback('OnClick', function()
----        print('clicked')
----        for k, v in pairs(button.frame) do
----            print(k)
----        end
----    end)
----    container:AddChild(button)
----end
----
------ function that draws the widgets for the second tab
----local function DrawGroup2(container)
----    local desc = AceGUI:Create("Label")
----    desc:SetText("This is Tab 2")
----    desc:SetFullWidth(true)
----    container:AddChild(desc)
----
----    local button = addon.CreateRealAceButton('Button', 200)
----    container:AddChild(button)
----end
----
------ Callback function for OnGroupSelected
----local function SelectGroup(container, event, group)
----    container:ReleaseChildren()
----    if group == "tab1" then
----        DrawGroup1(container)
----    elseif group == "tab2" then
----        DrawGroup2(container)
----    end
----end